
languageName = "English"
title = "Dune Shell"
copyright = "© Adam McDaniel :: 2021 - 2024"
enableGitInfo = true
enableRobotsTXT = true

[params]
  subtitle = "A shell🐚 by the beach🏖️!"
  owner = "Adam McDaniel"
  keywords = "Shell"
  copyright = "Adam McDaniel"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"
  minuteReadingTime = "min read"
  words = "words"

[params.logo]
  logoText = "Dune Shell"
  logoHomeLink = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/posts/about"
    weight=10
  [[menu.main]]
    identifier = "install"
    name = "Install"
    url = "/posts/install"
    weight=20
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/posts/showcase"
    weight=30
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/adam-mcdaniel/dune"
    weight=40
